### ISSUE TITLE
References to theme_aardvark in the code

### ISSUE THREAD

**Issue by mudrd8mz** [Casarecompensas/Educacion-Be#1]
I already raised this in the comment on 15 Apr 2015 at the Plugins directory page. 

You kept references to Shaun's `theme_aardvark` in several places in the code - including in some really critical places such as `settings.php`. As a consequences, your theme's setting may interfere/overwrite other theme's setting, and there are likely to be related bugs.

On contrary, you did not leave a single note anywhere in the code (or the plugin description here) that your theme is based on someone else's work. The General Public License is clear about this (see http://www.gnu.org/licenses/gpl-faq.html#IWantCredit) and in open source community, these things matter.

**Comment by mudrd8mz** [comment]
Also the `choosereadme` string reads

> Educacionbe is a three column theme for Moodle 2.5+ originally created by Shaun Daubney
> for <a href="http://www.newbury-college.ac.uk">Newbury College</a> based on Bootstrap

Is this correct? I understood that this theme was created by yourself, using Shaun's theme as an initial template.

**Comment by educacionbe-online** [comment]
It is a template created from Shaun tem, as the template that one began to be started either.

**Comment by danmarsden** [comment]
so... the theme wasn't "originally created" by Shaun... the educacion them was created by you, but based on Shauns theme. so you need to update the "choosereadme" string.

 Your README.txt file should also be updated to state that your theme is based on Shauns original work.

**Comment by educacionbe-online** [comment]
Hello. Mr. Marsden, update the issue with me mo is indicated in mesaje you. Thanks and regards.

**Comment by educacionbe-online** [comment]
Hello. Mr. Marsden, update the file name in the lib.php. Changing: educacionbe_process_css function
Should be:
theme_educacionbe_process_css
Thanks greetings.

**Comment by danmarsden** [comment]
please review the text again in readme.txt you have written " based on the original theme Shauns."  - you should really provide his fullname and the name of the theme you have based this on.

**Comment by educacionbe-online** [comment]
Hello danmarsden. And rename the theme and full name.

**Comment by mudrd8mz** [comment]
Looks like this can be closed now.
