### ISSUE TITLE
config.old kept in the code

### ISSUE THREAD

**Issue by mudrd8mz** [Casarecompensas/Educacion-Be#2]

**Comment by danmarsden** [comment]
config.old still appears to be there - shouldn't this be removed?

**Comment by educacionbe-online** [comment]
Hello. Mr. Marsden, the config.old file was deleted completely.
Thanks greetings.

**Comment by danmarsden** [comment]
you should delete it from your github branch too - it still shows there.

**Comment by educacionbe-online** [comment]
Hello. Mr. Marsden, the config.old file was deleted completely.
Thanks greetings.

**Comment by mudrd8mz** [comment]
Thanks
